<?php
/**
 *  ___   ____ _
 * / _ \ / ___| | __ _ ___ ___ _ __ ___   ___  _ __ ___
 *| | | | |   | |/ _` / __/ __| '__/ _ \ / _ \| '_ ` _ \
 *| |_| | |___| | (_| \__ \__ \ | | (_) | (_) | | | | | |
 * \__\_\\____|_|\__,_|___/___/_|  \___/ \___/|_| |_| |_|
 * 青草课堂 - index.phtml
 * Copyright (c) 2015 - 2019.,QCTech ,All rights reserved.
 * Created by: QCTech
 * Created Time: 2019-02-24 - 17:20
 */
if(DEMO){
?>

    <div class="layui-container">
        <div class="layui-carousel" id="carousel-home">
            <div carousel-item>
                <div id="carousel-1">
                    <img alt="海老师物理课堂" title="海老师物理课堂" src="https://i.loli.net/2019/02/26/5c75319f23a70.png" style="clear: both; display: block;margin:auto;" class="layui-hide-lg" />
                    <img alt="海老师物理课堂" title="海老师物理课堂" src="https://i.loli.net/2019/02/26/5c7531b6c8b7a.png" style="clear: both; display: block;margin:auto;" />
                </div>
                <div>
                    <img alt="青草课堂测试视频" title="青草课堂测试视频" src="https://i.loli.net/2019/02/26/5c753a5954b26.png" style="clear: both; display: block;margin:auto;" class="layui-hide-lg" />
                    <img alt="青草课堂测试视频" title="青草课堂测试视频" src="https://i.loli.net/2019/02/26/5c753a6db7591.png" style="clear: both; display: block;margin:auto;" />
                </div>
            </div>
        </div>
    </div>
<script>
    layui.use('carousel', function(){
        const carousel = layui.carousel;
        carousel.render({
            elem: '#carousel-home'
            ,width: '100%' //设置容器宽度
            ,anim: 'fade'
        });
    });
</script>
<?php } ?>