<?php
/**
 *  ___   ____ _
 * / _ \ / ___| | __ _ ___ ___ _ __ ___   ___  _ __ ___
 *| | | | |   | |/ _` / __/ __| '__/ _ \ / _ \| '_ ` _ \
 *| |_| | |___| | (_| \__ \__ \ | | (_) | (_) | | | | | |
 * \__\_\\____|_|\__,_|___/___/_|  \___/ \___/|_| |_| |_|
 * 青草课堂 - index.phtml
 * Copyright (c) 2015 - 2019.,QCTech ,All rights reserved.
 * Created by: QCTech
 * Created Time: 2019-02-24 - 17:20
 */
if(DEMO){
?>
    <div class="layui-container">
    <div id="player"></div>
    </div>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/dplayer@1.25.0/dist/DPlayer.min.css">
<style>
    .player-logo {
        pointer-events: none;
        position: absolute;
        right: 20px;
        top: 20px;
        max-width: 150px;
        max-height: 50px;
    }
    .player-logo img {
        max-width: 100%;
        max-height: 100%;
        background: none;
    }
</style>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/dplayer@1.25.0/dist/DPlayer.min.js"></script>
<script>
    const dp = new DPlayer({
        container: document.getElementById('player'),
        screenshot: true,
        theme: '#5FB878',
        mutex: true,
        logo: '/assets/img/logo_.png',
        video: {
            url: '/data/麻枝 准×やなぎなぎ 「終わりの世界から」.mp4',
            //pic: 'demo.jpg',
            //thumbnails: 'thumbnails.jpg'
        },
        subtitle: {
            color: '#cdcdcd',
            fontSize : '40px',
            url: '/data/%E7%BB%88%E3%82%8F%E3%82%8A%E3%81%AE%E4%B8%96%E7%95%8C%E3%81%8B%E3%82%89.vtt'
        },
    });
    $('.dplayer-logo').addClass('player-logo');
    $('.dplayer-logo').removeClass('dplayer-logo');
</script>
<?php } ?>