<div class="layui-container">
    <h1 style="text-align: center;"><?php echo $Config["website"]["title"]; ?>使用必读</h1>
    <hr />
    <h2>技术要求</h2>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">    理论上说，<?php echo $Config["website"]["title"]; ?>支持所有人类使用的现代化浏览器，如Chrome, Firefox；
    <br />如果您在使用过时的浏览器（如IE8/9或国产双核浏览器IE内核）,建议您切换至<a href="https://www.google.cn/intl/zh-CN_ALL/chrome/" target="_blank">Google Chrome</a>以获得最佳的用户体验。
    <br /><?php echo $Config["website"]["title"]; ?>目前尚不保证在移动端的学习体验。
    <br />如果依然不能解决问题，请提交<a href="https://github.com/qcminecraft/qc_classroom/issues" target="_blank">Issue</a>，并且告知浏览器的具体版本型号和操作系统版本。我们会尽力为您排查解决。
    </p>
</div>
