<?php
/**
 *  ___   ____ _
 * / _ \ / ___| | __ _ ___ ___ _ __ ___   ___  _ __ ___
 *| | | | |   | |/ _` / __/ __| '__/ _ \ / _ \| '_ ` _ \
 *| |_| | |___| | (_| \__ \__ \ | | (_) | (_) | | | | | |
 * \__\_\\____|_|\__,_|___/___/_|  \___/ \___/|_| |_| |_|
 * 青草课堂 - privacy-policy.phtml
 * Copyright (c) 2015 - 2019.,QCTech ,All rights reserved.
 * Created by: QCTech
 * Created Time: 2019-02-22 - 20:13
 */
?>
<div id="write" class="layui-container">
    <h1><a name="header-n268" ></a>青草课堂隐私政策</h1>
    <hr /><h2><a name="header-n0" ></a>引言</h2>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">青草课堂重视用户的隐私。您在使用我们的服务，我们可能会收集和使用您的相关信息。我们希望通过本《隐私政策》向您说明，在使用我们的服务时，我们如何收集、使用、储存和分享这些信息，以及我们为您提供的访问、更新、控制和保护这些信息的方式。本《隐私政策》与您所使用的青草课堂服务息息相关，我们也希望您能够仔细阅读，并在需要时，按照本《隐私政策》的指引，作出您认为适当的选择。本《隐私政策》中涉及的相关技术词汇，我们尽量以简明扼要的表述向您解释，并提供了进一步说明的链接，以便您的理解。</p>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;"><strong>您使用或继续使用我们的服务，都表示您同意我们按照本《隐私政策》收集、使用、储存和分享您的信息。</strong></p>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">如您对本《隐私政策》或与本《隐私政策》相关的事宜有任何问题，与我们联系。</p>
    <hr /><h2><a name="header-n138" ></a>我们可能收集的信息</h2>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">我们提供服务时，可能会收集、储存和使用下列与您有关的信息。如果您不提供相关信息，可能无法注册成为我们的用户、享受我们提供的某些服务，或者即便我们可以继续向您提供一些服务，也无法达到该服务拟达到的效果。</p>
    <hr /><h2><a name="header-n141" ></a>您提供的信息</h2>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">您在注册我们的账户或使用我们的服务时，填写、提交及/或其他任何方式向我们提供的相关个人信息。 </p>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">您通过我们的服务向其他方提供的共享信息，以及您使用我们的服务时所储存的信息。</p>
    <hr /><h2><a name="header-n273" ></a>获取的您的信息</h2>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">您使用我们服务时我们可能收集如下信息：</p>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;"><strong>日志信息</strong>指您使用我们服务时，系统可能会通过 cookies 或其他方式自动采集的技术信息，包括：</p>
    <ul>
        <li>设备或软件信息，例如您的移动设备、网页浏览器或您用于接入我们的服务的其他程序所提供的配置信息、您的IP地址和您的移动设备所用的版本和设备识别码；</li>
        <li>您在使用我们服务时搜索和浏览的信息，例如您使用的网页搜索词语、访问的社交媒体页面url地址，以及您在使用我们服务时浏览或要求提供的其他信息和内容详情；</li>
        <li>您通过我们的服务分享的内容所包含的信息（元数据），例如拍摄或上传的共享照片或录像的日期、时间等。</li>
    </ul>
    <hr /><h2><a name="header-n297" ></a>我们可能如何使用信息</h2>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">我们可能将在向您提供服务的过程之中所收集的信息用作下列用途：</p>
    <ul>
        <li>向您提供服务；</li>
        <li>在我们提供服务时，用于身份验证、客户服务、存档和备份用途，确保我们向您提供的产品和服务的安全性；</li>
        <li>帮助我们设计新服务，改善我们现有服务；</li>
        <li>使我们更加了解您如何接入和使用我们的服务，从而针对性地回应您的个性化需求，例如个性化的帮助服务和指示，或对您和其他使用我们服务的用户作出其他方面的回应；</li>
        <li>软件认证或管理软件升级；</li>
        <li>让您参与有关我们产品和服务的调查；</li>
    </ul>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">为了让您有更好的体验、改善我们的服务或您同意的其他用途，在符合相关法律法规的前提下，我们可能将通过我们的某一项服务所收集的信息，以汇集信息或者个性化的方式，用于我们的其他服务。例如，在您使用我们的一项服务时所收集的信息，可能在另一服务中用于向您提供特定内容，或向您展示与您相关的、非普遍推送的信息。如果我们在相关服务中提供了相应选项，您也可以授权我们将该服务所提供和储存的信息用于我们的其他服务。</p>
    <hr /><h2><a name="header-n172" ></a>您如何访问和控制自己的个人信息</h2>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">我们将尽一切可能采取适当的技术手段，保证您可以访问、更新和更正自己的注册信息或使用我们的服务时提供的其他个人信息。在访问、更新、更正您的个人信息时，我们可能会要求您进行身份验证，以保障您的账户安全。</p>
    <hr /><h2><a name="header-n175" ></a>我们可能分享的信息</h2>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">除以下情形外，<strong>未经您同意</strong>，我们不会与任何第三方分享您的个人信息：</p>
    <ul>
        <li>
            <p class="layui-text" style="font-size: 17px; line-height: 2em;">我们可能将您的个人信息、合作伙伴及第三方服务供应商、承包商分享（他们可能并非位于您所在法域），用作下列用途：</p>
            <ul>
                <li>向您提供我们的服务；</li>
                <li>实现“我们可能如何使用信息”部分所述目的；</li>
                <li>履行我们在《青草课堂用户使用协议》 或本《隐私政策》中的义务和行使我们的权利；</li>
                <li>理解、维护和改善我们的服务。</li>
                <li>如我们与任何上述第三方分享您的个人信息，我们将努力确保该等第三方在使用您的个人信息时遵守本《隐私政策》及我们要求其遵守的其他适当的保密和安全措施。</li>
            </ul>
        </li>
    </ul>
    <ul>
        <li>
            <p class="layui-text" style="font-size: 17px; line-height: 2em;">随着我们业务的持续发展，我们有可能进行合并、收购、资产转让或类似的交易，您的个人信息有可能作为此类交易的一部分而被转移。我们将在转移前通知您。</p>
            <ul>
                <li>我们还可能为以下需要保留、保存或披露您的个人信息：</li>
                <li>遵守适用的法律法规；</li>
                <li>遵守法院命令或其他法律程序的规定；</li>
                <li>遵守相关政府机关的要求；</li>
                <li>为遵守适用的法律法规、维护社会公共利益、或保护我们、其他用户的人身和财产安全或合法权益所合理必需的用途。</li>
            </ul>
        </li>
    </ul>
    <hr /><h2><a name="header-n359" ></a>信息安全</h2>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">我们仅在本《隐私政策》所述目的所必需期间和法律法规要求的时限内保留您的个人信息。</p>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">我们使用各种安全技术和程序，以防信息的丢失、不当使用、未经授权阅览或披露。例如，在某些服务中，我们将利用加密技术（例如SSL）来保护您提供的个人信息。但请您谅解，由于技术的限制以及以及可能存在的各种恶意手段，在互联网行业，即便竭尽所能加强安全措施，也不可能始终保证信息百分之百的安全。您需要了解，您接入我们的服务所用的系统和通讯网络，有可能因我们可控范围外的情况而发生问题。</p>
    <hr /><h2><a name="header-n196" ></a>您分享的敏感个人信息</h2>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">某些个人信息因其特殊性可能被认为是敏感个人信息，例如您的种族、宗教、个人健康和医疗信息等。相比其他个人信息，敏感个人信息受到更加严格的保护。</p>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">请注意，您在我们的服务中所提供、上传或发布的内容和信息，可能会泄露您的敏感个人信息。您需要谨慎地考虑，是否在使用我们的服务时披露相关敏感个人信息。</p>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;"><strong>您同意您的敏感个人信息按本《隐私政策》所述的目的和方式来处理。</strong></p>

    <hr /><h2><a name="header-n208" ></a>我们可能如何收集信息</h2>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">我们或我们的第三方合作伙伴，可能通过 cookies  收集和使用您的信息，并将该等信息储存为日志信息。</p>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">我们使用自己的 cookies ，目的是为您提供更个性化的用户体验和服务，并用于以下用途：</p>
    <ul>
        <li>记住您的身份。例如：cookies  有助于我们辨认您作为我们的注册用户的身份，或保存您向我们提供有关您的喜好或其他信息；</li>
        <li>分析您使用我们服务的情况。例如，我们可利用 cookies  来了解您使用我们的服务进行什么活动、或哪些网页或服务最受欢迎；</li>
        <li>cookies 有助于我们根据您的信息。</li>
    </ul>
    <hr /><h2><a name="header-n231" ></a>我们可能向您发送的邮件和信息</h2>
    <h3 class="layui-text" style="font-size: 17px; line-height: 2em;"><b>邮件和信息推送</b></h3>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">您在使用我们的服务时，我们可能使用您的信息向您的设备发送电子邮件、新闻或推送通知。如您不希望收到这些信息，可以按照我们的相关提示，在设备上选择取消订阅。</p>
    <h3 class="layui-text" style="font-size: 17px; line-height: 2em;"><b>与服务有关的公告</b></h3>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">我们可能在必需时（例如因系统维护而暂停某一项服务时）向您发出与服务有关的公告。您可能无法取消这些与服务有关、性质不属于推广的公告。</p>

    <hr /><h2><a name="header-n238" ></a>隐私政策的适用例外</h2>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">我们的服务可能包括或链接至第三方提供的社交媒体或其他服务（包括网站）。例如：</p>
    <ul>
        <li>您利用“分享”键将某些内容分享到我们的服务，或您利用第三方连线服务登录我们的服务。这些功能可能会收集您的相关信息（包括您的日志信息），并可能在您的电脑装置 cookies，从而正常运行上述功能；</li>
        <li>我们通过广告或我们服务的其他方式向您提供链接，使您可以接入第三方的服务或网站。</li>
    </ul>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">该等第三方社交媒体或其他服务可能由相关的第三方或我们运营。您使用该等第三方的社交媒体服务或其他服务（包括您向该等第三方提供的任何个人信息），须受该第三方的服务条款及隐私政策（而非《青草课堂用户使用协议》或本《隐私政策》）约束，您需要仔细阅读其条款。
        <br /><strong>本《隐私政策》仅适用于我们所收集的信息，并不适用于任何第三方提供的服务或第三方的信息使用规则，我们对任何第三方使用由您提供的信息不承担任何责任。</strong></p>

    <hr /><h2><a name="header-n248" ></a>隐私政策的适用范围</h2>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">除某些特定服务外，我们所有的服务均适用本《隐私政策》。这些特定服务将适用特定的隐私政策。<strong>针对某些特定服务的特定隐私政策，将更具体地说明我们在该等服务中如何使用您的信息。</strong>该特定服务的隐私政策构成本《隐私政策》的一部分。<strong>如任何特定服务的隐私政策与本《隐私政策》有不一致之处，则适用特定服务的隐私政策。</strong></p>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">除本《隐私政策》另有规定外，本《隐私条款》所用词语将与《青草课堂用户使用协议》 所定义的词语具有相同的涵义。</p>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">请您注意，本《隐私政策》不适用于以下情况：</p>
    <ul>
        <li>通过我们的服务而接入的第三方服务（包括任何第三方网站）收集的信息；</li>
    </ul>

    <hr /><h2><a name="header-n408" ></a>变更</h2>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">我们可能适时修订本《隐私政策》的条款，该等修订构成本《隐私政策》的一部分。<strong>如该等修订造成您在本《隐私政策》下权利的实质减少，我们将在修订生效前通过在网站显著位置提示或向您发送电子邮件或以其他方式通知您，在该种情况下，若您继续使用我们的服务，即表示同意受经修订的本《隐私政策》的约束。</strong></p>

    <p class="layui-text" style="font-size: 17px; line-height: 2em;"> </p>
    <p class="layui-text" style="font-size: 17px; line-height: 2em;">青草课堂</p>
</div>